### ISSUE TITLE
英文输入会有两段

### ISSUE THREAD

**Issue by y1rn** [Cantoboard/Cantoboard#100]
![image](https://user-images.githubusercontent.com/70128797/169036870-0e87dfba-42ec-4493-95b8-809a4c27c48a.png)

请问点样可以去除

**Comment by alex-the-man** [comment]
兩段係指即打即出。中間顯示嘅Input Buffer係for你編輯Input Buffer之用。打錯碼試下掃喺空白鍵向左掃，可以移動Input Caret修正Input Buffer.

**Comment by graphemecluster** [comment]
噉點解唔整多個模式直接移動輸入框嘅 caret？既方便隨時改前面嘅詞，又唔使有條 bar 係度掗住。

**Comment by alex-the-man** [comment]
之前個版本咪噉做囉，有超多兼容性問題先改成噉。直接移動caret會trigger好多app嘅autocomplete。會搞到好多app打唔到字。

**Comment by y1rn** [comment]
可唔可以唔要英文修改
