### ISSUE TITLE
Issue about automatic screen up and inset text 

### ISSUE THREAD

**Issue by Attiv** [Cantoboard/Cantoboard#101]
Thanks for all the help so many times! 

**What I want:**
Insert the typed key after a committed text has been inserted like this: (When I type `nini`, the output is `你们你们` 
![](https://raw.githubusercontent.com/Attiv/tubed/master/CleanShot%202022-05-30%20at%2017.37.05.gif)

**What I did**:
I have added a judgment in `InputController:updateInputState()`  : 
```
let text = rimeInputEngine!.getCommitedText()

if (state.inputMode != .english && text.count > 0) {
  insertText(text)
  clearInput()
}
```
But these will auto insert text and clear the key will be typed like this:  (When I type `nini`, the output is `你们i`)
![](https://raw.githubusercontent.com/Attiv/tubed/master/CleanShot%202022-05-30%20at%2017.44.40.gif)

The image is a bit large and may take a while to load.

I have debugged some methods but they do not work. Could u please help me again? Very thanks.

If these bother you please close it. Thanks

**Comment by alex-the-man** [comment]
Did you add the code snippet before processChar() is called?

**Comment by Attiv** [comment]
I have added that auto inserting word with four keys pressed. If using precessChar(), there will be a duplicate key like this:
(我 : wopd)
![](https://raw.githubusercontent.com/Attiv/tubed/master/CleanShot%202022-06-06%20at%2010.19.58.gif)
