### ISSUE TITLE
Option to change default $ sign to other currency symbol

### ISSUE THREAD

**Issue by sdugoten** [Cantoboard/Cantoboard#15]
For example , an option to allow you to change the key $ sign to £ sign in the keyboard

![keyboard](https://user-images.githubusercontent.com/7108552/123000307-542a7580-d3a7-11eb-8b3d-06a88de12fde.jpg)

Of course, that is not limited to £ sign.  It can be ¥　for Yen .  An option that allow you to choose the default currency symbol would be helpful.  The existing behaivor of holding on the currency sign show you a popup window to choose other currency should stay as well.  Thanks.

**Comment by alex-the-man** [comment]
https://github.com/Cantoboard/Cantoboard/commit/ac07e9e96ef9b44e8b7cb2dd723748f321a35985

**Comment by sdugoten** [comment]
Can you please send me invitation for beta redeem on TestFlight again please?

**Comment by alex-the-man** [comment]
Please give me a moment, I'm working on #13. Then I will publish a build. Sorry for the wait. Something unexpected caught me in real life.

**Comment by alex-the-man** [comment]
I've submitted the new TestFlight build to Apple. It's pending for review.

**Comment by sdugoten** [comment]
It works.  However, instead of using the locale to determine the dollar sign, it might be a better idea to have that as an option in the setting to change what country symbol to use.   I am pretty sure quite a few HK ppl use Japan region (in order to add Suica card into the wallet) while they actually live in Hong Kong.

**Comment by alex-the-man** [comment]
Yen is in the long press list. To avoid having too many config, I decided to stick with behavior of the iOS default keyboard.
