### ISSUE TITLE
功能建議

### ISSUE THREAD

**Issue by JACKCHAN000** [Cantoboard/Cantoboard#18]
本人為速成輸入法的使用者，ios的速成輸入法多年來都沒有太大的改進，希望增加多些功能以吸引更多使用者。

1. 希望增加導入用戶詞庫的功能

2. 增加關閉在候選欄顯示粵拼的選項：
使用速成的情況下無法關閉

3. 增加速成對中英混打的支持

**Comment by alex-the-man** [comment]
> 希望增加導入用戶詞庫的功能
呢個係roadmap入面, 但因爲iOS sandbox限制, 需要有啲複雜先做到. 暫時未有時間開始.

> 增加關閉在候選欄顯示粵拼的選項
呢個輸入法其中一個原意係推廣多啲人學廣東話拼音, 保育廣東話同埋等流散各地嘅廣東話使用者有自學廣東話和教下一代廣東話嘅能力. 請問你有興趣一試嗎?

> 增加速成對中英混打的支持
我研究一下, 希望可以做到.

**Comment by JACKCHAN000** [comment]
> 
> > 增加關閉在候選欄顯示粵拼的選項
> 
> 呢個輸入法其中一個原意係推廣多啲人學廣東話拼音, 保育廣東話同埋等流散各地嘅廣東話使用者有自學廣東話和教下一代廣東話嘅能力. 請問你有興趣一試嗎?

我都好明白推廣廣東話拼音嘅重要性，但係我認為速成入門容易，識寫就識打，可以降低學廣東話嘅門檻。
另外速成嘅用家始終比較多，個人認為可以俾一個選項用家去自由選擇，去增加cantoboard嘅用家數目。cantoboard唔單只粵拼好用，連速成都好用過其他d app好多，所以希望你地可以繼續努力。

**Comment by alex-the-man** [comment]
明白. 我會喺下個 official build 加個 option 完全關閉粵拼顯示.

**Comment by JACKCHAN000** [comment]
> 明白. 我會喺下個 official build 加個 option 完全關閉粵拼顯示.

感謝👍🏻

另外我發現左兩個bug
1. 在中文輸入法為速成的情況下使用英文輸入法，按enter會輸入倉頡碼而不是英文字。
2. 繁簡切換在速成下無效

**Comment by alex-the-man** [comment]
> 在中文輸入法為速成的情況下使用英文輸入法，按enter會輸入倉頡碼而不是英文字。

感謝彙報. 會fix

> 繁簡切換在速成下無效
繁簡中文字因爲本身個字唔同, 拆字形碼亦都唔同.  如果support繁簡切換, 會出現打繁體形碼出簡體字嘅奇怪情況(反之亦然), 會令使用者好困惑. 所以個設計係俾使用者用自己打嘅形碼去定繁體簡體, 而唔依靠轉換.

**Comment by JACKCHAN000** [comment]
感謝👍🏻

**Comment by alex-the-man** [comment]
> 在中文輸入法為速成的情況下使用英文輸入法，按enter會輸入倉頡碼而不是英文字。

https://github.com/Cantoboard/Cantoboard/commit/dd357e29d2f5d34f59037432d86a33bcac2709cf

> 增加關閉在候選欄顯示粵拼的選項

https://github.com/Cantoboard/Cantoboard/commit/dd357e29d2f5d34f59037432d86a33bcac2709cf

喺度我想借個機會再鼓勵一下閣下花少少時間學習粵拼, 保育廣東話. 用粵拼打字, 一來好適合輸入廣東話口語, 二來亦可以正音同埋改善懶音.
喺而家嘅社會狀態下, 如果我哋再抱住以前效率就是一切, 覺得打字最緊要快的話嘅香港精神的話, 廣東話只會被取代. 係唔係每人都可以行多一步, 從生活起捍衞本土文化呢?

**Comment by alex-the-man** [comment]
I've published the build to TestFlight: https://testflight.apple.com/join/zq9YSjuv

**Comment by alex-the-man** [comment]
> 增加速成對中英混打的支持

請問你同埋一般倉頡/速成嘅使用者, 係唔係會記得晒英文字母同字根嘅mapping? 還是係混打模式, 應該好似Kaiboard咁英文同字根都顯示?

**Comment by JACKCHAN000** [comment]
> > 增加速成對中英混打的支持
> 
> 請問你同埋一般倉頡/速成嘅使用者, 係唔係會記得晒英文字母同字根嘅mapping? 還是係混打模式, 應該好似Kaiboard咁英文同字根都顯示?

我係記得曬d mapping，因為其實實體嘅鍵盤都冇倉頡嘅字根。
至於好似Kaiboard咁英文同字根都顯示，有當然最好，冇都冇咩所謂。

**Comment by alex-the-man** [comment]
https://testflight.apple.com/join/zq9YSjuv 新build support速成中英混打

**Comment by JACKCHAN000** [comment]
更新左beta版之後，速成嘅選字好似怪怪地，好多詞組好似都打唔出。
![image](https://user-images.githubusercontent.com/61930699/130349802-3aa05f81-e837-4be9-a2bf-5d5adc005c74.png)

**Comment by alex-the-man** [comment]
I just pushed build 1.1.5 (6). That should fix the issue.
