### ISSUE TITLE
dictionary of quick5 are  inconsistent with cangjie5

### ISSUE THREAD

**Issue by TsinamLeung** [Cantoboard/Cantoboard#19]
I noticed that quick5.dict.yaml are 7k line less than cangjie5, I guess there might be some character missing in quick5. 

**Solution**:
  copy and rename cangjie5.dict.yaml to quick5.dict.yaml then edit the meta info of quick5.

_further promotion:_
quick5 should sort by weight, add some vocabulary using preset-vocabulary.

**Comment by alex-the-man** [comment]
Let me write a script to convert Cangjie5.dict into Quick5.dict.

**Comment by alex-the-man** [comment]
https://github.com/Cantoboard/Cantoboard/commit/b17f13ccd6f388c82d809094a05c7ee83cd76248
