### ISSUE TITLE
iPad 鍵盤佈局建議

### ISSUE THREAD

**Issue by noknok012** [Cantoboard/Cantoboard#21]
希望可以將鍵盤嘅第三行zxcvbnm向左移半格，啫係同Apple 個英文鍵盤一樣
鑑於iPad 熒幕較大並且無法用外接鍵盤，用户打字時需要雙手騰空，按照現時嘅鍵盤佈局，與標準鍵盤佈局不一，比搞容易撳錯掣。

**Comment by alex-the-man** [comment]
感謝你嘅意見. 我將會大執 iPad 界面, 等佢更加接近builtin iPad keyboard.

**Comment by alex-the-man** [comment]
你好, 係TestFlight嘅Beta版已經有大幅改良咗嘅iPad layout. 如果有時間, 可以試試, 被俾意見.

**Comment by alex-the-man** [comment]
你好, app store個build 已經有最新 iPad support. 歡迎試用, 提供 feedback.
