### ISSUE TITLE
一啲问题和建议

### ISSUE THREAD

**Issue by y1rn** [Cantoboard/Cantoboard#27]
多谢cantoboard 刚使用咗一下觉得几好用，打算用一段时间试试

ENV: iphone 12，IOS 14.8

# 下面系发现嘅问题：

![image](https://user-images.githubusercontent.com/70128797/133751610-c0648c77-caed-4f55-ab58-a4f1fff4960c.png)
- 下拉搜索输入会一直有选中状态

- ~~设定咗空白键输出候选，都仲系输出英文~~

- emoji分类不能滑动

![image](https://user-images.githubusercontent.com/70128797/133787378-aeae7d14-2ee0-4d35-8b58-0afc50faa251.png)
- github,webssh下变成横屏

# 建议：
- 提供取消emojii button选项，因为系统自带就有
- 添加emoji混输(类似rime-emoji，觉得哩个功能年轻人中意)

**Comment by y1rn** [comment]
> 多谢cantoboard 刚使用咗一下觉得几好用，打算用一段时间试试
> 
> ENV: iphone 12，IOS 14.8
> 
> # 下面系发现嘅问题：
> ![image](https://user-images.githubusercontent.com/70128797/133751610-c0648c77-caed-4f55-ab58-a4f1fff4960c.png)
> 
> * 下拉搜索输入会一直有选中状态
> * 设定咗空白键输出候选，都仲系输出英文
> * emoji分类滑动失效
> 
> # 建议：
> * 提供取消emojii button选项，因为系统自带就有
> * 添加emoji混输(类似rime-emoji，觉得哩个功能年轻人中意)

**Comment by y1rn** [comment]
喺測試版發現簡體輸出選項冇咗，希望可以保留

**Comment by alex-the-man** [comment]
> 喺測試版發現簡體輸出選項冇咗，希望可以保留
嗰個選項因為iOS sandboxing嘅關係唔work, 所以畀我剷左. 但輸入法依舊有簡體輸入功能.

按一下呢個掣就可以切換繁簡
![image](https://user-images.githubusercontent.com/8400790/133867587-743c4a81-955d-4121-a36e-a79fd322ccb9.png)

**Comment by alex-the-man** [comment]
> github,webssh下变成横屏
請問喺測試版仲有冇呢個問題?

**Comment by y1rn** [comment]
> > github,webssh下变成横屏
> 
> 
> 
> 請問喺測試版仲有冇呢個問題?

有

**Comment by alex-the-man** [comment]
> > > github,webssh下变成横屏
> > 
> > 
> > 
> > 請問喺測試版仲有冇呢個問題?
> 
> 有

請問呢個係隨機出現嘅bug,還是一定出現嘅bug?

如果係呢個時候，你unlock screen rotation lock, 然後旋轉屏幕至打橫再旋轉返直，會令佢變返正常嗎？

我係iPhone X嘅GitHub app hit唔到呢個問題。可能係iPhone 12 specific.我會係出一個新測試版去加啲logs。請等半天。之後要麻煩你俾logs我。

**Comment by y1rn** [comment]
> 如果係呢個時候，你unlock screen rotation lock, 然後旋轉屏幕至打橫再旋轉返直，會令佢變返正常嗎？

打横之后可以用，再打直一样都系展示不全

**Comment by alex-the-man** [comment]
請upgrade到TestFlight 1.1.6 (9), 記得allow full access:
![image](https://user-images.githubusercontent.com/8400790/133906973-e8d83d79-91ee-4d7e-b4a8-d55e2d282c98.png)

然後, 當問題出然後, 長按emoji key, select "logs":
![image](https://user-images.githubusercontent.com/8400790/133907011-5f4bde61-e0f7-42f9-b989-560dc6086317.png)

然後share log file給我. 謝謝.
![image](https://user-images.githubusercontent.com/8400790/133907020-fefc0324-23f3-4c44-bd22-068044b5690b.png)

**Comment by y1rn** [comment]
> > > > github,webssh下变成横屏
> > > 
> > > 
> > > 請問喺測試版仲有冇呢個問題?
> > 
> > 
> > 有
> 
> 請問呢個係隨機出現嘅bug,還是一定出現嘅bug?
> 
> 如果係呢個時候，你unlock screen rotation lock, 然後旋轉屏幕至打橫再旋轉返直，會令佢變返正常嗎？
> 
> 我係iPhone X嘅GitHub app hit唔到呢個問題。可能係iPhone 12 specific.我會出一個新測試版去加啲logs。請等半天。之後要麻煩你俾logs我。

[logs-1632006657.003652.zip](https://github.com/Cantoboard/Cantoboard/files/7190762/logs-1632006657.003652.zip)

**Comment by alex-the-man** [comment]
Bug confirmed:
```
2021-09-19 07:10:52:266 [KeyboardViewController:77]: refreshLayoutConstants Screen size (390.0, 844.0) superview size (0.0, 0.0, 375.0, 198.0)
2021-09-19 07:10:52:266 [KeyboardViewController:86]: iPad special mode debug UIDevice userInterfaceIdiom 0 traitCollection <UITraitCollection: 0x282cc52b0; UserInterfaceIdiom = Phone, DisplayScale = 3, DisplayGamut = P3, HorizontalSizeClass = Compact, VerticalSizeClass = Regular, UserInterfaceStyle = Light, UserInterfaceLayoutDirection = LTR, ForceTouchCapability = Unavailable, PreferredContentSizeCategory = L, AccessibilityContrast = Normal, UserInterfaceLevel = Base>
2021-09-19 07:10:52:266 [KeyboardViewController:101]: refreshLayoutConstants reportedScreenSize (390.0, 844.0) correctedScreenSize (844.0, 390.0)
```

**Comment by alex-the-man** [comment]
> 提供取消emojii button选项，因为系统自带就有

因為iOS冇提供API畀thrid party keyboard switch to Emoji keyboard, 如果唔想使用者下下要用地球掣切換到emoji keyboard 的話, 就要複製iOS本身個keyboard.

**Comment by y1rn** [comment]
> > 提供取消emojii button选项，因为系统自带就有
> 
> 
> 
> 因為iOS冇提供API畀thrid party keyboard switch to Emoji keyboard, 如果唔想使用者下下要用地球掣切換到emoji keyboard 的話, 就要複製iOS本身個keyboard.

我依家只用cantoboard，地球掣可以用嚟切换emoji,就觉得同emoji掣功能重复,可能其他用户有多个输入法用返emoji掣方便啲

**Comment by y1rn** [comment]
下拉搜索输入会一直有选中状态,哩个问题依然喺度

**Comment by alex-the-man** [comment]
> 下拉搜索输入会一直有选中状态,哩个问题依然喺度

唔好意思, 唔係好明. 請問你可以post一段video畀我了解下個問題喺邊度嗎?

**Comment by alex-the-man** [comment]
Emoji scrolling: https://github.com/Cantoboard/Cantoboard/commit/8c42e0f7a7a8a546d0aac2b929e4445a37b47ff0

**Comment by alex-the-man** [comment]
呢個問題係iOS marked text API 引起嘅. Marked Text API兼容度實在太差. 要 fix 呢個問題, 要靠 #26. 捨棄 Marked Text API, 用Kaiboard式 immediate mode去處理input.

**Comment by alex-the-man** [comment]
1.1.6 (11) 有 emoji swipe scrolling. 可以測試一下?

**Comment by y1rn** [comment]
> 1.1.6 (11) 有 emoji swipe scrolling. 可以測試一下?

好嘅thx

**Comment by alex-the-man** [comment]
@y1rn emoji swipe scrolling ok嗎? 如果ok, 我想正式出個build.

**Comment by y1rn** [comment]
> @y1rn emoji swipe scrolling ok嗎? 如果ok, 我想正式出個build.

可以用thx

**Comment by alex-the-man** [comment]
最新build亦都有搜尋文字被highlight嘅fix.

**Comment by y1rn** [comment]
> 最新build亦都有搜尋文字被highlight嘅fix.

thx, 我试试

**Comment by alex-the-man** [comment]
請問仲有冇問題？如果冇，我可以close咗呢個issue先嗎？另外開一個issue track打字出emoji功能。

**Comment by y1rn** [comment]
> 請問仲有冇問題？如果冇，我可以close咗呢個issue先嗎？另外開一個issue track打字出emoji功能。

ok
