### ISSUE TITLE
缺少数字键盘

### ISSUE THREAD

**Issue by y1rn** [Cantoboard/Cantoboard#28]
阿里云盘app等号码输入框下，手机号码输入不能切换成号码键盘（系统键盘和gboard可以），输入数字只能上屏一位

**Comment by alex-the-man** [comment]
請問可以post個screenshot嗎

**Comment by y1rn** [comment]
> 請問可以post個screenshot嗎

![Uploading 133884838...]()

**Comment by y1rn** [comment]
> > 請問可以post個screenshot嗎
> 
> ![image](https://user-images.githubusercontent.com/70128797/133884878-c44c7f47-9113-4374-88e8-03212c383514.gif)

试咗好几个地方嘅input field，只要系数字键盘都系一样

**Comment by alex-the-man** [comment]
This should fix the problem: https://github.com/Cantoboard/Cantoboard/commit/a393cce7cc8af841abb52a598a416d16f313c603

I will release a build soon.

**Comment by alex-the-man** [comment]
請upgrade到TestFlight 1.1.6 (9), 記得allow full access:
![image](https://user-images.githubusercontent.com/8400790/133906973-e8d83d79-91ee-4d7e-b4a8-d55e2d282c98.png)

然後, 當問題出然後, 長按emoji key, select "logs":
![image](https://user-images.githubusercontent.com/8400790/133907011-5f4bde61-e0f7-42f9-b989-560dc6086317.png)

然後share log file給我. 謝謝.
![image](https://user-images.githubusercontent.com/8400790/133907020-fefc0324-23f3-4c44-bd22-068044b5690b.png)

**Comment by y1rn** [comment]
> 我喺TestFlight build 1.1.6 (9) fix咗

可以输入喇，thx
