### ISSUE TITLE
iphone 12 layout issue

### ISSUE THREAD

**Issue by y1rn** [Cantoboard/Cantoboard#29]
![image](https://user-images.githubusercontent.com/70128797/133910881-6d34300d-ee6a-4b6e-933e-fb5a1dd88de3.png)

**Comment by alex-the-man** [comment]
請問你可以好似另一個issue咁畀logs我嗎？Logs入面有dimensions, 請係水平模式俾logs我。唔該。

**Comment by y1rn** [comment]
> 請問你可以好似另一個issue咁畀logs我嗎？Logs入面有dimensions, 請係水平模式俾logs我。唔該。

[logs-1632032299.707293.zip](https://github.com/Cantoboard/Cantoboard/files/7191082/logs-1632032299.707293.zip)

**Comment by alex-the-man** [comment]
請問你可以capture一個screenshot顯示iOS 系統鍵盤打橫打直有幾闊嗎? 唔該.

**Comment by alex-the-man** [comment]
另外, 請問喺iPhone 12, 會唔會喺唔同時候, iOS系統鍵盤/screen會有唔同闊度? 會唔會有時候屏幕兩面有黑邊會窄咗少少?

**Comment by y1rn** [comment]
> 請問你可以capture一個screenshot顯示iOS 系統鍵盤打橫打直有幾闊嗎? 唔該.

![image](https://user-images.githubusercontent.com/70128797/133919858-bc944407-e23b-458e-86e9-796517524eaf.png)


![image](https://user-images.githubusercontent.com/70128797/133919860-6a0830da-6fab-4e72-962c-5c409a7b753b.png)

![image](https://user-images.githubusercontent.com/70128797/133919869-1411896e-21bf-4553-9231-38c42ed7b657.png)

**Comment by y1rn** [comment]
> 另外, 請問喺iPhone 12, 會唔會喺唔同時候, iOS系統鍵盤/screen會有唔同闊度? 會唔會有時候屏幕兩面有黑邊會窄咗少少? 我無實機, Simulator係呢個case唔能夠準確模擬實機.

冇发现哩个问题

**Comment by alex-the-man** [comment]
Could you try the latest TestFlight build: 1.1.6 (10)?

**Comment by y1rn** [comment]
> Could you try the latest TestFlight build: 1.1.6 (10)?

可以喇 thx.
