### ISSUE TITLE
safari 输入网址过程中点击地址栏没有清除候选

### ISSUE THREAD

**Issue by y1rn** [Cantoboard/Cantoboard#33]
![image](https://user-images.githubusercontent.com/70128797/135464164-1f4d2a47-482d-488e-8e5d-ce9a59966839.gif)

**Comment by alex-the-man** [comment]
Will fix once I come back from vacation

**Comment by alex-the-man** [comment]
因為 iOS 冇 expose selected text 俾 custom keyboard, 所以我 fix 唔到...

**Comment by y1rn** [comment]
> The fix is available on TestFlight build 1.1.7. Could you verify?

ok喇 thx
