### ISSUE TITLE
长时间不使用会lag

### ISSUE THREAD

**Issue by y1rn** [Cantoboard/Cantoboard#35]
可能process被kill咗

device: iphone 12
os version: iOS 15.0.1

**Comment by alex-the-man** [comment]
請問lag係乜嘢意思? 打字慢，定係第一次load番出嚟要loading？

**Comment by y1rn** [comment]
> 請問lag係乜嘢意思? 打字慢，定係第一次load番出嚟要loading？

需要loading,琴晚ipad 使用期间唔同app切换都有遇到

**Comment by alex-the-man** [comment]
Could you test the latest build 1.1.9 (0) on TestFlight?

**Comment by alex-the-man** [comment]
Do you see any improvement or any regression?

**Comment by y1rn** [comment]
初时安装新版会lag一吓，其他暂时没有发现会重新load

**Comment by y1rn** [comment]
好似仲系会出现，而家变咗输入框内全部空白，大概持续一秒左右

**Comment by alex-the-man** [comment]
可唔可以錄條片睇睇？喺乜嘢情況下會出現？

**Comment by y1rn** [comment]
> 可唔可以錄條片睇睇？喺乜嘢情況下會出現？

耐唔耐出现一次，我睇下录唔录得到

**Comment by alex-the-man** [comment]
你可以長按 emoji 掣，係 debug menu 選擇 exit 去手動 restart keyboard.

**Comment by y1rn** [comment]
填写讯息验证码时候都会出现空白
![image](https://user-images.githubusercontent.com/70128797/142346696-b96d482a-253d-418f-8f51-0a4f092eea86.jpeg)
并且验证码提示唔会出现

点击其他地方离开再点击输入框又会出现cantobaord

**Comment by alex-the-man** [comment]
可唔可以錦吓個地球掣 check 吓 係唔係 iOS 轉咗輸入法？

**Comment by y1rn** [comment]
> 可唔可以㩒吓個地球掣 check 吓 係唔係 iOS 轉咗輸入法？

冇转，都系cantoboard

**Comment by y1rn** [comment]
> > 可唔可以㩒吓個地球掣 check 吓 係唔係 iOS 轉咗輸入法？
> 
> 冇转，都系cantoboard

试多几次应该系网页接收短讯时候会出现，应该系属于另一个bug

**Comment by alex-the-man** [comment]
請問有冇其他app可以repo到個issue？

**Comment by y1rn** [comment]
> 請問有冇其他app可以repo到個issue？

未有发现

**Comment by alex-the-man** [comment]
請問你可唔可以俾logs我？

請先係第二個app用Cantoboard鍵盤，然後switch去呢個app reproduce個bug。之後：
1. 同時間撳實 Volume Up + Volume Down + Power 三個掣
2. 等 1s or 1.5s
3. 三個掣同時間放手，部iPhone應該會長震一下
4. 等10分鐘
5. Settings > Privacy > Analytics > Analytis Data
6. 揾sysdiagnose開頭嘅log，揀最新嗰個share比我

**Comment by y1rn** [comment]
> 請問你可唔可以俾logs我？
> 
> 請先係第二個app用Cantoboard鍵盤，然後switch去呢個app reproduce個bug。之後：
> 
> 1. 同時間撳實 Volume Up + Volume Down + Power 三個掣
> 2. 等 1s or 1.5s
> 3. 三個掣同時間放手，部iPhone應該會長震一下
> 4. 等10分鐘
> 5. Settings > Privacy > Analytics > Analytis Data
> 6. 揾sysdiagnose開頭嘅log，揀最新嗰個share比我

里边好多数据,你需要边啲

**Comment by alex-the-man** [comment]
> 揾sysdiagnose開頭嘅log，揀最新嗰個share比我

![image](https://user-images.githubusercontent.com/8400790/143993025-1fd12813-26a8-41a2-afad-3c0ff0e8e98a.png)

**Comment by y1rn** [comment]
> > 揾sysdiagnose開頭嘅log，揀最新嗰個share比我
> 
> ![image](https://user-images.githubusercontent.com/8400790/143993025-1fd12813-26a8-41a2-afad-3c0ff0e8e98a.png)

sysdiagnose 268mb比较大,你需要边啲文件,我挑出嚟畀你

**Comment by alex-the-man** [comment]
system_logs.logarchive

**Comment by y1rn** [comment]
> system_logs.logarchive

太大放唔上github

**Comment by alex-the-man** [comment]
請問你可唔可以email cantoboard@gmail.com?

**Comment by alex-the-man** [comment]
如果情況惡化，請再開新issue。
