### ISSUE TITLE
safari 网页input field 长揿del掣删除字符问题

### ISSUE THREAD

**Issue by y1rn** [Cantoboard/Cantoboard#43]
OS: IOS 15.0.2

e.g.
www.google.com 网页input field输入
```td.pls:first-child > ul.xl.xl2.o.cl```
然后长揿del,delete到```>```就会停住

**Comment by alex-the-man** [comment]
I'm unable to find a workaround. Could you try reproducing the same issue in a normal text field? If you cannot repo the bug, then we can conclude that it's caused by iOS. Thanks.

**Comment by y1rn** [comment]
暂时冇揾到其他field有哩个情况, 不过试过其他输入法是可以正常delete嘅, 例如: gboard, irime, jyutping

**Comment by alex-the-man** [comment]
可以試吓喺 TestFlight 最新嗰個 build 嗎？

**Comment by y1rn** [comment]
试咗吓可以delete到喇, thx
