### ISSUE TITLE
Incorrect keyboard height in iPad Mini 6

### ISSUE THREAD

**Issue by lenchan139** [Cantoboard/Cantoboard#44]
Hello, 
on the iPad mini 6 (iOS 15.0.2) with vertical position, the keyboard will show like this:

![image](https://user-images.githubusercontent.com/3122461/138226936-dc3ec480-0f56-4d26-98df-622c94b5bfe1.png)

and the build-in keyboard should be like this:
![image](https://user-images.githubusercontent.com/3122461/138226979-585c49f6-c69d-4e7c-9632-eb8aa7c5a421.png)

**Comment by alex-the-man** [comment]
https://github.com/Cantoboard/Cantoboard/commit/2318e6c48343faef885e3f69b5b58bfd6881957e

**Comment by alex-the-man** [comment]
The build on TestFlight is pending review

**Comment by alex-the-man** [comment]
The build is available here: https://testflight.apple.com/join/zq9YSjuv

**Comment by lenchan139** [comment]
![image](https://user-images.githubusercontent.com/3122461/140051364-59070162-25cc-42a6-96e8-303844f3872e.png)
![image](https://user-images.githubusercontent.com/3122461/140051376-89b188d4-1823-42c2-a3ac-70fcfa4ed7a3.png)


work with the testflight build very well. thank for your quick response :)
