### ISSUE TITLE
输入法选项消失

### ISSUE THREAD

**Issue by y1rn** [Cantoboard/Cantoboard#58]
OS: IOS 15.0.2
software version: 1.1.18(16)
others desc: 没有开｢允许完全访问｣,之前几个测试版本都有发现哩个问题.

issue:
 有时候切换app会发现cantoboard输入法消失,需要去会设定重新添加

**Comment by alex-the-man** [comment]
呢個係 iOS 15 嘅 bug. 影響所有 third party keyboard extensions. 我哋只能夠望天打卦等 Apple fix 呢個問題。

**Comment by y1rn** [comment]
之前冇出现哩个问题,近排先有

**Comment by alex-the-man** [comment]
其他使用者 report 過出現問題後 reboot 會減少出現次數。另外亦都有使用者 report 過 upgrade 15.1 之後，呢個問題嘅出現頻率由日日出現，減低做幾日出現一次。

**Comment by y1rn** [comment]
我依家开翻[允许完全访问](唔知有冇影响)睇下会唔会再出现, 再出现我再试吓reboot

**Comment by alex-the-man** [comment]
> 我依家开翻[允许完全访问](%E5%94%94%E7%9F%A5%E6%9C%89%E5%86%87%E5%BD%B1%E5%93%8D)睇下会唔会再出现, 再出现我再试吓reboot

可能 flip 一 filp Full Access 嗰個 toggle 係一個快過 reboot 嘅 workaround. 如果 work，麻煩你喺到 report 一下，等我話畀其他 users 知道。

**Comment by y1rn** [comment]
> > 我依家开翻[允许完全访问](%E5%94%94%E7%9F%A5%E6%9C%89%E5%86%87%E5%BD%B1%E5%93%8D)睇下会唔会再出现, 再出现我再试吓reboot
> 
> 
> 
> Flip 一 filp full Access 好可能係快過 reboot 嘅 workaround. 如果 work，麻煩你喺到 report 一下，等我話畀其他 users 知道。

而家除咗安装新test版本时候试过需要重新添加之外无点出现过

**Comment by y1rn** [comment]
> > > 我依家开翻[允许完全访问](%E5%94%94%E7%9F%A5%E6%9C%89%E5%86%87%E5%BD%B1%E5%93%8D)睇下会唔会再出现, 再出现我再试吓reboot
> > 
> > 
> > 
> > Flip 一 filp full Access 好可能係快過 reboot 嘅 workaround. 如果 work，麻煩你喺到 report 一下，等我話畀其他 users 知道。
> 
> 好似都仲系有
