### ISSUE TITLE
Where is the NumKeyRow.swift file?

### ISSUE THREAD

**Issue by Attiv** [Cantoboard/Cantoboard#60]
I got the error: Build input file cannot be found: '/Users/xxx/NumKeyRow.swift' when building.
I found the NumKeyRow.swift file path was location at my User directory

**Comment by alex-the-man** [comment]
My bad I broke the build

**Comment by alex-the-man** [comment]
Fixed here: https://github.com/Cantoboard/Cantoboard/commit/6bbf7fca8dccb70d3685199c4b0ea0318210ee2f
