### ISSUE TITLE
有时输入前会有残影

### ISSUE THREAD

**Issue by y1rn** [Cantoboard/Cantoboard#65]
类似
![image](https://user-images.githubusercontent.com/70128797/141978701-31c7f07d-2e1b-4244-ac73-7c435666e72f.jpeg)

**Comment by alex-the-man** [comment]
請問呢個殘影會唔會自己消失？

**Comment by y1rn** [comment]
出现一吓就消失

**Comment by alex-the-man** [comment]
呢個係因為 iOS 係 user 打緊字嘅時候 take 咗 screenshot. 個 app restore 嘅時候會用嗰個 screenshot. @graphemecluster 請問你會唔會咁啱知道，點樣可以控制 iOS 幾時 take screenshot?

**Comment by graphemecluster** [comment]
係咪有個 library cache 嘅 folder，嗰度搵唔搵到 snapshot？
詳細點控制我就唔知嘞，但係你試過其他 UIInputViewController 嘅 method 未？

**Comment by alex-the-man** [comment]
I tried to hide all pressed keys on applicationwillresignactive/applicationdidenterbackground. It doesn't make a difference.
Do you see the same behaviour in other third party keyboards?

**Comment by y1rn** [comment]
> I tried to hide all pressed keys on applicationwillresignactive/applicationdidenterbackground. It doesn't make a difference.
> 
> Do you see the same behaviour in other third party keyboards?  

之前一直用gboard冇发现哩个问题

**Comment by alex-the-man** [comment]
I dug into this a bit more. I believe it has something to do with frame skipping. I will attempt to eliminate frame skipping and see if it resolves the problem.

**Comment by alex-the-man** [comment]
I eliminated frame skipping and yet the problem persists.

**Comment by y1rn** [comment]
试过短时间使用其他输入法(搜狗, irmie)没有发现同样问题

**Comment by alex-the-man** [comment]
Once I wrap up predictive text, I will try reducing the keyboard load time to avoid showing the screenshot.

**Comment by y1rn** [comment]
1.1.10都发现过一次

**Comment by alex-the-man** [comment]
冇辦法完全eliminate個問題. 請問出現頻率有冇降低?

**Comment by graphemecluster** [comment]
我見到有明顯嘅改善，不過喺打開新 app 撳 text field 開 Cantoboard 嘅時候，有十分一機會會開唔到而跳咗去另一個 custom keyboard

**Comment by alex-the-man** [comment]
> 我見到有明顯嘅改善，不過喺打開新 app 撳 text field 開 Cantoboard 嘅時候，有十分一機會會開唔到而跳咗去另一個 custom keyboard

請問問呢個出現嘅頻率會唔會decay? 會唔會係因為我改咗 keyboard language 導致? https://github.com/Cantoboard/Cantoboard/commit/fde9ad6397f7827f60364d7bfdaef1068017c84c

**Comment by y1rn** [comment]
> 冇辦法完全eliminate個問題. 請問出現頻率有冇降低?

貌似出现少咗

**Comment by graphemecluster** [comment]
> 請問問呢個出現嘅頻率會唔會decay? 會唔會係因為我改咗 keyboard language 導致? [fde9ad6](https://github.com/Cantoboard/Cantoboard/commit/fde9ad6397f7827f60364d7bfdaef1068017c84c)

間唔時都會出現，我都唔係好清楚，使唔使 send 啲 log 之類畀你？
啊，同埋開閂 keyboard 個 FPS 好似慢咗

**Comment by alex-the-man** [comment]
如果情況惡化，請再開新issue。
