### ISSUE TITLE
How to make automatic screen up?

### ISSUE THREAD

**Issue by Attiv** [Cantoboard/Cantoboard#70]
- I modify the rime config. And set `max_code_length: 4`. But the input dismiss after typing 4 words.
- how to make Space key as commiting
![CleanShot 2021-11-24 at 15 35 27](https://user-images.githubusercontent.com/15698129/143194916-15f40efa-4c7e-4343-82cc-ea74ce386c4d.gif)

**Comment by alex-the-man** [comment]
https://github.com/Cantoboard/Cantoboard/blob/main/CantoboardFramework/Keyboard/InputController.swift#L620

Call RimeInputEngine.getComposedText() in this function. If the returned string isn't empty, call InputController.insertText().

**Comment by Attiv** [comment]
> https://github.com/Cantoboard/Cantoboard/blob/main/CantoboardFramework/Keyboard/InputController.swift#L620
> 
> Call RimeInputEngine.getComposedText() in this function. If the returned string isn't empty, call InputController.insertText().

Thanks. But I got `RimeInputEngine.composition?.text = nil` when I typed `wopd`

**Comment by alex-the-man** [comment]
Oops. I meant rimeSession.getCommitedText(). You might need to add a method in RimeInputEngine to expose the method.

**Comment by Attiv** [comment]
> 

Thx, it works
