### ISSUE TITLE
`r`, `v`, `x`, `q` shortcut support for Jyutping

### ISSUE THREAD

**Issue by graphemecluster** [Cantoboard/Cantoboard#80]
In the Yale schema, there are
https://github.com/Cantoboard/Cantoboard/blob/ef3ae7a185c1eec1998896dc3b7aabfbcacc8170/CantoboardFramework/Data/Rime/yale.schema.yaml#L77-L84
(Ignore Line 78-81)

Could you also add these lines to the Jyutping non-vxq schema?
Furthermore, shall we make a vxq-schema for Yale removing these lines?

**Comment by alex-the-man** [comment]
I'm open to the change. I didn't make the change as so far no user has complained.
