### ISSUE TITLE
how to make ngram?

### ISSUE THREAD

**Issue by Attiv** [Cantoboard/Cantoboard#81]
I want to use zh_cn instead of zh_hk.ngram, but I can't find how to make ngram file. Can you help me? Thanks a lot

**Comment by alex-the-man** [comment]
Prepare a CSV file similar to: https://github.com/Cantoboard/Cantoboard/blob/main/NGramBuilder/ngram.csv
Please note that total_freq is not used and not required. freq is the conditional probability of the occurrence of the last char given the prefix string.
e.g.: 
```
一個,0.24010566461033062
```
P('個|一') = 0.24010566461033062

Then compile and run https://github.com/Cantoboard/Cantoboard/blob/main/NGramBuilder/main.cpp to generated the ngram.

**Comment by Attiv** [comment]
Thanks a lot!

**Comment by alex-the-man** [comment]
I added simplified predicted text support: https://github.com/Cantoboard/Cantoboard/blob/main/CantoboardFramework/Data/InstallToCache/NGram/zh_CN.ngram

It's still based on Cantonese not Mandarin so I'm not sure it's what you are looking for.
