### ISSUE TITLE
Fine tune cursor initialCursorMovingThreshold

### ISSUE THREAD

**Issue by alex-the-man** [Cantoboard/Cantoboard#94]

**Comment by alex-the-man** [comment]
f0b941b635374489f270f004ab6b2dfde62bbca7

**Comment by graphemecluster** [comment]
Still too sensitive for all iPad models. Could you please make the values of `cursorMovingStepX` and `swipeXThreshold` keyboard-layout-specific (i.e. use 4 different values for each of them)?

Also, for models that do not support force touch, it should be able to use two fingers to achieve the same effect without using the space bar.

Thanks in advance. 🙏🏻

**Comment by alex-the-man** [comment]
> For models that do not support force touch, Could you make it able to use two fingers to achieve the same effect without using the space bar? Thanks in advance. 🙏🏻

Is the same function available only on iPad's stock keyboard?

**Comment by graphemecluster** [comment]
> Is the same function available only on iPad's stock keyboard?
I think so.
