### ISSUE TITLE
速成下空白鍵的保留輸入部份情況下會失效

### ISSUE THREAD

**Issue by JACKCHAN000** [Cantoboard/Cantoboard#95]
空白鍵的設置是保留輸入

當輸入英文字典出現的單字沒有問題
![image](https://user-images.githubusercontent.com/61930699/163326120-b7674569-615e-42f3-bfc8-5d654b356ea2.gif)

但當輸入字典沒有的單字按空白鍵會輸出倉頡碼，而不是英文字符。
![image](https://user-images.githubusercontent.com/61930699/163326373-25115426-1ac4-427d-adc6-e636589ca98b.gif)

但使用粵拼則沒有問題

希望可以修復這個bug，感謝。

**Comment by alex-the-man** [comment]
收到。我睇睇。

**Comment by alex-the-man** [comment]
1b292c9ccd1c27917e6036cde44a28e8ac52f0ad

**Comment by alex-the-man** [comment]
TestFlight 最新版 1.1.11 14 有呢個fix。

**Comment by JACKCHAN000** [comment]
唔該曬～
