### ISSUE TITLE
How to support LUA like rime.lua on Mac rime

### ISSUE THREAD

**Issue by Attiv** [Cantoboard/Cantoboard#99]
I have looked through the codes and lib-rime, but I can't find how to support Lua. Could you please help with it? Thanks.

**Comment by alex-the-man** [comment]
Create a symlink to the module under librime/plugin.
Then use my build script to build rime. Make sure it contains this change: https://github.com/Cantoboard/librime-ios-build/commit/ec58f74187f555174f60850ab10bfa09f0e577eb

**Comment by Attiv** [comment]
> 

Thanks. You are so cool! But I met some issues. Just like :
```
The following build commands failed:
	PhaseScriptExecution CMake\ Rules /Users/xxx/iOSGithub/librime-ios-build/build/librime/macosx_x86_64/proto/rime.build/Release/rime-proto-objs.build/Script-E424EE6D7BBF4A61AF8888B4.sh
(1 failure)
```
Here are my handles: 
1. git clone https://github.com/Cantoboard/librime-ios-build
2. git submodule update --init
3. git clone https://github.com/Cantoboard/librime
4. add https://github.com/Cantoboard/librime-cantoboard to librime/plugins
5. add https://github.com/hchunhui/librime-lua to librime/plugins
6. `bash boost.sh`, but got error "Error staging Mac Catalyst"
7. `bash build-ios.sh librime_path`, got error: 
```
"librime-ios-build/output/thirdparty/macosx_x86_64/bin/capnp: No such file or directory
make: *** [/Users/xx/iOSGithub/librime-ios-build/build/librime/macosx_x86_64/proto/rime_proto.capnp.c++] Error 1

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution CMake\ Rules /Users/xx/iOSGithub/librime-ios-build/build/librime/macosx_x86_64/proto/rime.build/Release/rime-proto-objs.build/Script-D1545906ADE8491C9A156A8A.sh
(1 failure)"
```

I have done those for many times, but failed all the time.

**Comment by alex-the-man** [comment]
Could you try `build-ios.sh all librime_path`

**Comment by alex-the-man** [comment]
FYI iOS has strict memory usage limit. If the keyboard extension process uses > 66MB, iOS will kill it.

**Comment by Attiv** [comment]
> Could you try `build-ios.sh all librime_path`

Very thanks. But `build-ios.sh all librime_path` seems to be wrong while `build-ios.sh  librime_path all` works. But there is no xcframework generated when first run this. The console like this:
![CleanShot 2022-05-19 at 16 23 10@2x](https://user-images.githubusercontent.com/15698129/169248362-7f1f2e31-a7ef-4843-8cdb-6a818dede684.png)
 
When I run the `build-ios.sh  librime_path all` for second time. It shows: 
![CleanShot 2022-05-19 at 16 26 16@2x](https://user-images.githubusercontent.com/15698129/169248624-4bcf4d34-b876-4326-b84e-2c5233a941a2.png)

I have searched but can't solve.

**Comment by alex-the-man** [comment]
Could you run `uname -m` and post the output?

**Comment by Attiv** [comment]
> 

`x86_64` 

I'm sorry I'm not familiar with this, thank you.

**Comment by alex-the-man** [comment]
Are you building my fork https://github.com/Cantoboard/librime?

**Comment by Attiv** [comment]
Yes,and I add `https://github.com/Cantoboard/librime-cantoboard` and `https://github.com/hchunhui/librime-lua` to `librime/plugins`

**Comment by Attiv** [comment]
@alex-the-man 
Sorry to bother you again. I haven't been able to add lua-irime successfully so far. Could you please try to do it when you are free? Thanks very much

**Comment by alex-the-man** [comment]
Due to the strict memory constraint of iOS keyboard plugin, we are hesitant to add rime-lua to Cantoboard.
